### PR TITLE
ForSelect Fix

### PR DESCRIPTION
**Pull request by agdal1125**
- deleted print messages
- deleted min_feature variable
- fixed scoring error metric

### CODE REVIEW

**Comment by andrealee011** [comment]
what does this failed check mean? `codecov/patch — 0.00% of diff hit (target 93.88%)` and how do we fix it?

**Review by andrealee011 — CHANGES_REQUESTED** [review]
what does this failed check mean? `codecov/patch — 0.00% of diff hit (target 93.88%)` and how do we fix it? do you need to add more tests?

**Comment by andrealee011** [comment]
^ resolving merge conflict in docstring after my PR was merged

**Comment by agdal1125** [comment]
closing due to codecov patch issue.

**Comment by andrealee011** [comment]
reopening after fixing codecov patch

**Pull request closed without merging**
